Proof Of Concept ML - Algoritmo de Recomendaciones

In [ ]:
import pandas as pd

ML_BASE = pd.read_csv("ML_BASE.csv")
ML_Categorias = pd.read_csv("ML_Categorias.csv")

In [255]:
ML_MISC = MISC_Final

In [256]:
ML_MISC

,gmap_id,Service Option 1,Service Option 2,Accessibility 1,Accessibility 2,Popular_for 1,Popular_for 2,Popular_for 3,Crowd 1,Crowd 2,Payments 1,Payments 2,Payments 3,Highlights 1
0,0x80c2c778e3b73d33:0xbdc58662a4a97d49,1,2,1,0,0,0,0,0,0,0,0,0,0
1,0x80dd2b4c8555edb7:0xfc33d65c4bdbef42,1,2,1,0,1,2,3,0,0,0,0,0,0
2,0x87ec235c54d25b31:0x3b75fb5facc602f,0,2,0,0,0,0,0,0,0,0,0,0,0
3,0x884bdf439ee0d6e3:0x16676d0a5982954d,1,2,0,0,1,2,3,1,0,1,0,0,0
4,0x89c6c89efcaed69d:0xded973f6033e7dba,0,2,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240698,0x87c92eaea0fef483:0xb73c49fa00698f31,1,2,1,0,1,2,3,1,2,0,0,0,1
240699,0x8758ddd1bfd14845:0xfd904490a700f0e,1,0,1,0,1,2,3,1,0,0,0,0,0
240700,0x872ba99db0ab78db:0x55c826ed8748149d,1,0,1,2,1,2,3,1,0,1,0,3,0
240701,0x8758dd6a49d17909:0xbe7ccb53ee53e5a7,1,2,1,0,0,0,0,0,0,0,0,0,0
240702,0x880f96c84b0ef57b:0xe75b67b15a2cfdad,1,2,0,0,1,2,3,1,2,0,0,0,0

In [259]:
# Se devuelven los valores a ceros y unos para indicar presencia o ausencia de atributo.

# Reemplazar los valores según las especificaciones
ML_MISC['Service Option 2'] = ML_MISC['Service Option 2'].replace(2, 1)
ML_MISC['Accessibility 2'] = ML_MISC['Accessibility 2'].replace(2, 1)
ML_MISC['Popular_for 2'] = ML_MISC['Popular_for 2'].replace(2, 1)
ML_MISC['Popular_for 3'] = ML_MISC['Popular_for 3'].replace(3, 1)
ML_MISC['Crowd 2'] = ML_MISC['Crowd 2'].replace(2, 1)
ML_MISC['Payments 2'] = ML_MISC['Payments 2'].replace(2, 1)
ML_MISC['Payments 3'] = ML_MISC['Payments 3'].replace(3, 1)

In [260]:
ML_MISC

,gmap_id,Service Option 1,Service Option 2,Accessibility 1,Accessibility 2,Popular_for 1,Popular_for 2,Popular_for 3,Crowd 1,Crowd 2,Payments 1,Payments 2,Payments 3,Highlights 1
0,0x80c2c778e3b73d33:0xbdc58662a4a97d49,1,1,1,0,0,0,0,0,0,0,0,0,0
1,0x80dd2b4c8555edb7:0xfc33d65c4bdbef42,1,1,1,0,1,1,1,0,0,0,0,0,0
2,0x87ec235c54d25b31:0x3b75fb5facc602f,0,1,0,0,0,0,0,0,0,0,0,0,0
3,0x884bdf439ee0d6e3:0x16676d0a5982954d,1,1,0,0,1,1,1,1,0,1,0,0,0
4,0x89c6c89efcaed69d:0xded973f6033e7dba,0,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240698,0x87c92eaea0fef483:0xb73c49fa00698f31,1,1,1,0,1,1,1,1,1,0,0,0,1
240699,0x8758ddd1bfd14845:0xfd904490a700f0e,1,0,1,0,1,1,1,1,0,0,0,0,0
240700,0x872ba99db0ab78db:0x55c826ed8748149d,1,0,1,1,1,1,1,1,0,1,0,1,0
240701,0x8758dd6a49d17909:0xbe7ccb53ee53e5a7,1,1,1,0,0,0,0,0,0,0,0,0,0
240702,0x880f96c84b0ef57b:0xe75b67b15a2cfdad,1,1,0,0,1,1,1,1,1,0,0,0,0

In [268]:
# Nuevos nombres de columnas
nuevos_nombres = [
    'gmap_id', 
    'Takeout', 
    'Delivery', 
    'Asientos Discapacitados', 
    'Estacionamiento Discapacitados', 
    'Almuerzo', 
    'Cena', 
    'Comer Solo', 
    'Grupos', 
    'Turistas', 
    'Debito', 
    'NFC', 
    'Credito', 
    'Servicio Rapido'
]

ML_MISC.columns = nuevos_nombres

In [269]:
ML_MISC

,gmap_id,Takeout,Delivery,Asientos Discapacitados,Estacionamiento Discapacitados,Almuerzo,Cena,Comer Solo,Grupos,Turistas,Debito,NFC,Credito,Servicio Rapido
0,0x80c2c778e3b73d33:0xbdc58662a4a97d49,1,1,1,0,0,0,0,0,0,0,0,0,0
1,0x80dd2b4c8555edb7:0xfc33d65c4bdbef42,1,1,1,0,1,1,1,0,0,0,0,0,0
2,0x87ec235c54d25b31:0x3b75fb5facc602f,0,1,0,0,0,0,0,0,0,0,0,0,0
3,0x884bdf439ee0d6e3:0x16676d0a5982954d,1,1,0,0,1,1,1,1,0,1,0,0,0
4,0x89c6c89efcaed69d:0xded973f6033e7dba,0,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240698,0x87c92eaea0fef483:0xb73c49fa00698f31,1,1,1,0,1,1,1,1,1,0,0,0,1
240699,0x8758ddd1bfd14845:0xfd904490a700f0e,1,0,1,0,1,1,1,1,0,0,0,0,0
240700,0x872ba99db0ab78db:0x55c826ed8748149d,1,0,1,1,1,1,1,1,0,1,0,1,0
240701,0x8758dd6a49d17909:0xbe7ccb53ee53e5a7,1,1,1,0,0,0,0,0,0,0,0,0,0
240702,0x880f96c84b0ef57b:0xe75b67b15a2cfdad,1,1,0,0,1,1,1,1,1,0,0,0,0

In [283]:
restaurantes_limpios["Estado"]

0         CA
1         PA
2         CA
3         IN
4         NH
          ..
240698    AR
240699    WY
240700    AZ
240701    WY
240702    IL
Name: Estado, Length: 240703, dtype: object

In [284]:
# Obtener los valores únicos de la columna "Estado"
valores_unicos = restaurantes_limpios["Estado"].unique()

# Convertir a una lista (opcional)
valores_unicos_lista = valores_unicos.tolist()

# Imprimir los valores únicos
print(valores_unicos_lista)

['CA', 'PA', 'IN', 'NH', 'NY', 'TN', 'IL', 'TX', 'NV', 'LA', 'FL', 'AZ', 'CO', 'MA', 'UT', 'OR', 'VA', 'MD', 'DC', 'OK', 'NJ', 'GA', 'NC', 'WA', 'AR', 'RI', 'OH', 'WI', 'CT', 'MI', 'ID', 'SC', 'MN', 'HI', 'KY', 'IA', 'MS', 'MT', 'MO', 'ME', 'WV', 'NM', 'KS', 'DE', 'WY', 'VT', 'AK', 'NE', 'AL', 'ND', 'SD']

In [285]:
# Crear un diccionario que mapea las abreviaturas a los nombres de los estados
estado_dict = {
    'CA': 'California',
    'PA': 'Pennsylvania',
    'IN': 'Indiana',
    'NH': 'New Hampshire',
    'NY': 'New York',
    'TN': 'Tennessee',
    'IL': 'Illinois',
    'TX': 'Texas',
    'NV': 'Nevada',
    'LA': 'Louisiana',
    'FL': 'Florida',
    'AZ': 'Arizona',
    'CO': 'Colorado',
    'MA': 'Massachusetts',
    'UT': 'Utah',
    'OR': 'Oregon',
    'VA': 'Virginia',
    'MD': 'Maryland',
    'DC': 'District of Columbia',
    'OK': 'Oklahoma',
    'NJ': 'New Jersey',
    'GA': 'Georgia',
    'NC': 'North Carolina',
    'WA': 'Washington',
    'AR': 'Arkansas',
    'RI': 'Rhode Island',
    'OH': 'Ohio',
    'WI': 'Wisconsin',
    'CT': 'Connecticut',
    'MI': 'Michigan',
    'ID': 'Idaho',
    'SC': 'South Carolina',
    'MN': 'Minnesota',
    'HI': 'Hawaii',
    'KY': 'Kentucky',
    'IA': 'Iowa',
    'MS': 'Mississippi',
    'MT': 'Montana',
    'MO': 'Missouri',
    'ME': 'Maine',
    'WV': 'West Virginia',
    'NM': 'New Mexico',
    'KS': 'Kansas',
    'DE': 'Delaware',
    'WY': 'Wyoming',
    'VT': 'Vermont',
    'AK': 'Alaska',
    'NE': 'Nebraska',
    'AL': 'Alabama',
    'ND': 'North Dakota',
    'SD': 'South Dakota'
}

# Reemplazar las abreviaturas en la columna "Estado"
restaurantes_limpios['Estado'] = restaurantes_limpios['Estado'].replace(estado_dict)

# Verificar el resultado
print(restaurantes_limpios)

                                      gmap_id                          Nombre  \
0       0x80c2c7c9e450aad7:0x55f6a7ac45bad129            L'APPART by AIR FOOD
1       0x89c6b305f0dcfb8d:0x6d14e883fec24c42      Little Istanbul Restaurant
2       0x80dd2971a83ea65b:0xb1b8e4120e0b0348                     Garage Fish
3       0x886b57f69379908d:0xced3f89bd038e2c5    Homey Hot Pot & Sushi Buffet
4       0x89e1f86ecb300001:0x59cbfb48a60a2243                     Oak & Grain
...                                       ...                             ...
240698  0x87c92eaea0fef483:0xb73c49fa00698f31                      T&A Saloon
240699   0x8758ddd1bfd14845:0xfd904490a700f0e               Asian Cuisine # 2
240700  0x872ba99db0ab78db:0x55c826ed8748149d   Rosa’s Mexican Grill Chandler
240701  0x8758dd6a49d17909:0xbe7ccb53ee53e5a7                  Domino's Pizza
240702  0x880f96c84b0ef57b:0xe75b67b15a2cfdad  The Green Room Of Libertyville

               Estado  Promedio  Valoraciones  Categoria1  Categoria2  \
0          California       4.7            37       159.0         0.0
1        Pennsylvania       4.5           349        25.0       159.0
2          California       4.2             8        24.0         0.0
3             Indiana       4.5           278        21.0         0.0
4       New Hampshire       4.9            18        21.0       159.0
...               ...       ...           ...         ...         ...
240698       Arkansas       4.6            36       163.0         0.0
240699        Wyoming       4.3            38       157.0         0.0
240700        Arizona       4.4            88        30.0         0.0
240701        Wyoming       4.1           178        68.0       159.0
240702       Illinois       4.6           228        37.0        14.0

        Categoria3  Categoria4  Categoria5
0              0.0         0.0         0.0
1              0.0         0.0         0.0
2              0.0         0.0         0.0
3              0.0         0.0         0.0
4              0.0         0.0         0.0
...            ...         ...         ...
240698         0.0         0.0         0.0
240699         0.0         0.0         0.0
240700         0.0         0.0         0.0
240701         0.0         0.0         0.0
240702         0.0         0.0         0.0

[240703 rows x 10 columns]

In [286]:
restaurantes_limpios

,gmap_id,Nombre,Estado,Promedio,Valoraciones,Categoria1,Categoria2,Categoria3,Categoria4,Categoria5
0,0x80c2c7c9e450aad7:0x55f6a7ac45bad129,L'APPART by AIR FOOD,California,4.7,37,159.0,0.0,0.0,0.0,0.0
1,0x89c6b305f0dcfb8d:0x6d14e883fec24c42,Little Istanbul Restaurant,Pennsylvania,4.5,349,25.0,159.0,0.0,0.0,0.0
2,0x80dd2971a83ea65b:0xb1b8e4120e0b0348,Garage Fish,California,4.2,8,24.0,0.0,0.0,0.0,0.0
3,0x886b57f69379908d:0xced3f89bd038e2c5,Homey Hot Pot & Sushi Buffet,Indiana,4.5,278,21.0,0.0,0.0,0.0,0.0
4,0x89e1f86ecb300001:0x59cbfb48a60a2243,Oak & Grain,New Hampshire,4.9,18,21.0,159.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
240698,0x87c92eaea0fef483:0xb73c49fa00698f31,T&A Saloon,Arkansas,4.6,36,163.0,0.0,0.0,0.0,0.0
240699,0x8758ddd1bfd14845:0xfd904490a700f0e,Asian Cuisine # 2,Wyoming,4.3,38,157.0,0.0,0.0,0.0,0.0
240700,0x872ba99db0ab78db:0x55c826ed8748149d,Rosa’s Mexican Grill Chandler,Arizona,4.4,88,30.0,0.0,0.0,0.0,0.0
240701,0x8758dd6a49d17909:0xbe7ccb53ee53e5a7,Domino's Pizza,Wyoming,4.1,178,68.0,159.0,0.0,0.0,0.0
240702,0x880f96c84b0ef57b:0xe75b67b15a2cfdad,The Green Room Of Libertyville,Illinois,4.6,228,37.0,14.0,0.0,0.0,0.0

In [287]:
# Cambiar los tipos de columnas de float a int

# Selecciona todas las columnas de tipo float64
float_columns = restaurantes_limpios.select_dtypes(include=['float64']).columns

# Convierte a lista y omite la columna "Promedio"
float_columns = float_columns.drop('Promedio').tolist()
restaurantes_limpios[float_columns] = restaurantes_limpios[float_columns].astype(int)

In [288]:
restaurantes_limpios

,gmap_id,Nombre,Estado,Promedio,Valoraciones,Categoria1,Categoria2,Categoria3,Categoria4,Categoria5
0,0x80c2c7c9e450aad7:0x55f6a7ac45bad129,L'APPART by AIR FOOD,California,4.7,37,159,0,0,0,0
1,0x89c6b305f0dcfb8d:0x6d14e883fec24c42,Little Istanbul Restaurant,Pennsylvania,4.5,349,25,159,0,0,0
2,0x80dd2971a83ea65b:0xb1b8e4120e0b0348,Garage Fish,California,4.2,8,24,0,0,0,0
3,0x886b57f69379908d:0xced3f89bd038e2c5,Homey Hot Pot & Sushi Buffet,Indiana,4.5,278,21,0,0,0,0
4,0x89e1f86ecb300001:0x59cbfb48a60a2243,Oak & Grain,New Hampshire,4.9,18,21,159,0,0,0
...,...,...,...,...,...,...,...,...,...,...
240698,0x87c92eaea0fef483:0xb73c49fa00698f31,T&A Saloon,Arkansas,4.6,36,163,0,0,0,0
240699,0x8758ddd1bfd14845:0xfd904490a700f0e,Asian Cuisine # 2,Wyoming,4.3,38,157,0,0,0,0
240700,0x872ba99db0ab78db:0x55c826ed8748149d,Rosa’s Mexican Grill Chandler,Arizona,4.4,88,30,0,0,0,0
240701,0x8758dd6a49d17909:0xbe7ccb53ee53e5a7,Domino's Pizza,Wyoming,4.1,178,68,159,0,0,0
240702,0x880f96c84b0ef57b:0xe75b67b15a2cfdad,The Green Room Of Libertyville,Illinois,4.6,228,37,14,0,0,0

Combinar los dataframes para tener todo lo necesario en uno solo y luego asociar con las categorias

In [289]:
# Realizamos la unión de los DataFrames
ML_BASE = pd.merge(restaurantes_limpios, ML_MISC, on='gmap_id', suffixes=('', '_y'))

# Eliminamos la columna duplicada que termina en '_y'
ML_BASE = ML_BASE.loc[:, ~ML_BASE.columns.str.endswith('_y')]

# Ahora ML_BASE contiene la unión deseada

In [290]:
ML_BASE

,gmap_id,Nombre,Estado,Promedio,Valoraciones,Categoria1,Categoria2,Categoria3,Categoria4,Categoria5,...,Estacionamiento Discapacitados,Almuerzo,Cena,Comer Solo,Grupos,Turistas,Debito,NFC,Credito,Servicio Rapido
0,0x80c2c7c9e450aad7:0x55f6a7ac45bad129,L'APPART by AIR FOOD,California,4.7,37,159,0,0,0,0,...,0,1,1,1,0,0,1,0,0,0
1,0x89c6b305f0dcfb8d:0x6d14e883fec24c42,Little Istanbul Restaurant,Pennsylvania,4.5,349,25,159,0,0,0,...,0,1,1,1,1,1,1,1,1,0
2,0x80dd2971a83ea65b:0xb1b8e4120e0b0348,Garage Fish,California,4.2,8,24,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
3,0x886b57f69379908d:0xced3f89bd038e2c5,Homey Hot Pot & Sushi Buffet,Indiana,4.5,278,21,0,0,0,0,...,0,1,1,1,1,0,0,1,1,0
4,0x89e1f86ecb300001:0x59cbfb48a60a2243,Oak & Grain,New Hampshire,4.9,18,21,159,0,0,0,...,0,0,1,1,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240698,0x87c92eaea0fef483:0xb73c49fa00698f31,T&A Saloon,Arkansas,4.6,36,163,0,0,0,0,...,0,1,1,1,1,1,0,0,0,1
240699,0x8758ddd1bfd14845:0xfd904490a700f0e,Asian Cuisine # 2,Wyoming,4.3,38,157,0,0,0,0,...,0,1,1,1,1,0,0,0,0,0
240700,0x872ba99db0ab78db:0x55c826ed8748149d,Rosa’s Mexican Grill Chandler,Arizona,4.4,88,30,0,0,0,0,...,1,1,1,1,1,0,1,0,1,0
240701,0x8758dd6a49d17909:0xbe7ccb53ee53e5a7,Domino's Pizza,Wyoming,4.1,178,68,159,0,0,0,...,0,0,0,0,0,0,0,0,0,0
240702,0x880f96c84b0ef57b:0xe75b67b15a2cfdad,The Green Room Of Libertyville,Illinois,4.6,228,37,14,0,0,0,...,0,1,1,1,1,1,0,0,0,0

In [292]:
ML_Categorias = categorias_filtradas

In [296]:
ML_Categorias

French restaurant                 0
French steakhouse restaurant      1
Fusion restaurant                 2
Modern French restaurant          3
Pizza restaurant                  4
                               ...
Sfiha restaurant                346
Mutton barbecue restaurant      347
Steamboat restaurant            348
Sundanese restaurant            349
Tempura donburi restaurant      350
Length: 351, dtype: int64

In [295]:
ML_Categorias.info()

<class 'pandas.core.series.Series'>
Index: 351 entries, French restaurant to Tempura donburi restaurant
Series name: None
Non-Null Count  Dtype
--------------  -----
351 non-null    int64
dtypes: int64(1)
memory usage: 13.6+ KB

In [331]:
# Convertir la serie a un diccionario
diccionario_categorias = ML_Categorias.to_dict()

Primer Prueba ML

Primer aproximación

In [ ]:
import pandas as pd

def recomendar_restaurantes(df, categorias, estado, categorias_seleccionadas=None, promedio=None, valoraciones_min=1,
                            exclude_restaurante=None, takeout=None, delivery=None, 
                            asientos_discapacitados=None, estacionamiento_discapacitados=None,
                            almuerzo=None, cena=None, comer_solo=None, grupos=None, 
                            turistas=None, debito=None, nfc=None, credito=None,
                            servicio_rapido=None):

    # Validar el estado ingresado
    estados_validos = df['Estado'].unique()
    if estado not in estados_validos:
        return f"Estado '{estado}' no válido. Por favor, elige uno de los siguientes: {', '.join(estados_validos)}"

    # Filtrar por estado
    df_filtrado = df[df['Estado'].str.lower() == estado.lower()]

    # Si no hay restaurantes en el estado seleccionado, retornar un mensaje
    if df_filtrado.empty:
        return f"No se encontraron restaurantes en el estado '{estado}'."

    # Filtrar por categorías, si se proporcionan
    if categorias_seleccionadas:
        df_filtrado = df_filtrado[df_filtrado[['Categoria1', 'Categoria2', 'Categoria3', 'Categoria4', 'Categoria5']].apply(lambda x: x.isin(categorias_seleccionadas).any(), axis=1)]

    # Filtrar por promedio mínimo y valoraciones mínimas si se proporcionaron
    if promedio is not None:
        df_filtrado = df_filtrado[df_filtrado['Promedio'] >= promedio]
    df_filtrado = df_filtrado[df_filtrado['Valoraciones'] >= valoraciones_min]

    # Excluir restaurante si se proporciona y no es '0'
    if exclude_restaurante and exclude_restaurante != '0':
        df_filtrado = df_filtrado[df_filtrado['Nombre'].str.lower() != exclude_restaurante.lower()]

    # Calcular un puntaje de coincidencia
    df_filtrado['Puntaje'] = 0

    # Atributos a evaluar
    atributos = {
        'Takeout': takeout,
        'Delivery': delivery,
        'Asientos Discapacitados': asientos_discapacitados,
        'Estacionamiento Discapacitados': estacionamiento_discapacitados,
        'Almuerzo': almuerzo,
        'Cena': cena,
        'Comer Solo': comer_solo,
        'Grupos': grupos,
        'Turistas': turistas,
        'Debito': debito,
        'NFC': nfc,
        'Credito': credito,
        'Servicio Rapido': servicio_rapido
    }

    # Evaluar cada atributo y aumentar el puntaje
    for atributo, valor in atributos.items():
        if valor is not None:
            df_filtrado['Puntaje'] += df_filtrado[atributo].apply(lambda x: 1 if x == valor else 0)

    # Obtener recomendaciones, ordenadas por puntaje
    recomendaciones = df_filtrado.sort_values(by='Puntaje', ascending=False).drop_duplicates(subset='Nombre')

    # Si no hay recomendaciones, buscar alternativas
    if recomendaciones.empty:
        return "No se encontraron restaurantes que cumplan con los criterios."

    recomendaciones_info = []
    for index, row in recomendaciones.head(3).iterrows():
        cumplimiento = {}
        for atributo, valor in atributos.items():
            if valor is None:
                cumplimiento[atributo] = "No filtrado"
            elif row[atributo] == valor:
                cumplimiento[atributo] = "Cumple"
            else:
                cumplimiento[atributo] = "No cumple"
        recomendaciones_info.append({
            'Nombre': row['Nombre'],
            'Promedio': row['Promedio'],
            'Valoraciones': row['Valoraciones'],
            'Puntaje': row['Puntaje'],
            **cumplimiento
        })
    
    return pd.DataFrame(recomendaciones_info) if recomendaciones_info else "No se encontraron restaurantes que cumplan con los criterios."

# Asegúrate de que la función obtener_filtros siga siendo la misma, ya que esa parte está bien.

# Ejemplo de uso
# Asumiendo que ML_BASE es tu DataFrame de entrada con la información de los restaurantes
# Define ML_BASE con datos de ejemplo o reales antes de llamar a esta función
# Obtener filtros llamando a la función

obtener_filtros(ML_BASE)

Categorías disponibles:
1 - Comida Italiana
2 - Comida Mexicana
3 - Comida Rápida
4 - Comida Vegetariana
5 - Comida China
No se encontraron restaurantes que cumplan con los criterios.

In [332]:
diccionario_categorias

{'French restaurant': 0,
 'French steakhouse restaurant': 1,
 'Fusion restaurant': 2,
 'Modern French restaurant': 3,
 'Pizza restaurant': 4,
 'Turkish restaurant': 5,
 'Gyro restaurant': 6,
 'Halal restaurant': 7,
 'Mediterranean restaurant': 8,
 'Middle Eastern restaurant': 9,
 'Sushi restaurant': 10,
 'Burrito restaurant': 11,
 'Raw food restaurant': 12,
 'Seafood restaurant': 13,
 'Taco restaurant': 14,
 'Asian restaurant': 15,
 'Buffet restaurant': 16,
 'Chinese restaurant': 17,
 'Hot pot restaurant': 18,
 'Japanese restaurant': 19,
 'Fine dining restaurant': 20,
 'American restaurant': 21,
 'Brunch restaurant': 22,
 'Vegetarian restaurant': 23,
 'Bistro': 24,
 'Caribbean restaurant': 25,
 'Cocktail bar': 26,
 'Hookah bar': 27,
 'Austrian restaurant': 28,
 'European restaurant': 29,
 'German restaurant': 30,
 'Pizza Takeout': 31,
 'Breakfast restaurant': 32,
 'Gluten-free restaurant': 33,
 'Delivery Restaurant': 34,
 'Takeout Restaurant': 35,
 'Catering food and drink supplier': 36,
 'Mexican restaurant': 37,
 'Vegan restaurant': 38,
 'Izakaya restaurant': 39,
 'Authentic Japanese restaurant': 40,
 'Udon noodle restaurant': 41,
 'Yakitori restaurant': 42,
 'Laotian restaurant': 43,
 'Pho restaurant': 44,
 'Thai restaurant': 45,
 'Vietnamese restaurant': 46,
 'Asian fusion restaurant': 47,
 'Fast food restaurant': 48,
 'Lunch restaurant': 49,
 'Bulgarian restaurant': 50,
 'Eastern European restaurant': 51,
 'Romanian restaurant': 52,
 'Russian restaurant': 53,
 'Teppanyaki restaurant': 54,
 'Chicken restaurant': 55,
 'Spanish restaurant': 56,
 'Hawaiian restaurant': 57,
 'Polynesian restaurant': 58,
 'Hamburger restaurant': 59,
 'Japanese steakhouse': 60,
 'Bar & grill': 61,
 'Barbecue restaurant': 62,
 'Karaoke bar': 63,
 'Sports bar': 64,
 'Italian restaurant': 65,
 'Organic restaurant': 66,
 'Health food restaurant': 67,
 'New American restaurant': 68,
 'Traditional American restaurant': 69,
 'Tapas restaurant': 70,
 'Pan-Asian restaurant': 71,
 'Dim sum restaurant': 72,
 'Mandarin restaurant': 73,
 'Moroccan restaurant': 74,
 'Ramen restaurant': 75,
 'Rice restaurant': 76,
 'African restaurant': 77,
 'East African restaurant': 78,
 'South African restaurant': 79,
 'West African restaurant': 80,
 'Wine bar': 81,
 'Egyptian restaurant': 82,
 'Lebanese restaurant': 83,
 'Down home cooking restaurant': 84,
 'Diner': 85,
 'Family restaurant': 86,
 'English restaurant': 87,
 'Neapolitan restaurant': 88,
 'Northern Italian restaurant': 89,
 'Southern Italian restaurant': 90,
 'Chicken wings restaurant': 91,
 'Korean barbecue restaurant': 92,
 'Korean restaurant': 93,
 'Soup restaurant': 94,
 'Israeli restaurant': 95,
 'Kosher restaurant': 96,
 'Sichuan restaurant': 97,
 'Hot dog restaurant': 98,
 'Meat dish restaurant': 99,
 'Southern restaurant (US)': 100,
 'Latin American restaurant': 101,
 'Eclectic restaurant': 102,
 'Tex-Mex restaurant': 103,
 'Malaysian restaurant': 104,
 'Greek restaurant': 105,
 'Live music bar': 106,
 'Tapas bar': 107,
 'Ethnic restaurant': 108,
 'Traditional restaurant': 109,
 'Soul food restaurant': 110,
 'Armenian restaurant': 111,
 'Cantonese restaurant': 112,
 'Cheesesteak restaurant': 113,
 'Falafel restaurant': 114,
 'Modern European restaurant': 115,
 'Wedding bakery': 116,
 'Persian restaurant': 117,
 'Delivery Chinese restaurant': 118,
 'Brazilian restaurant': 119,
 'Cuban restaurant': 120,
 'Chinese noodle restaurant': 121,
 'Nuevo Latino restaurant': 122,
 'Colombian restaurant': 123,
 'Puerto Rican restaurant': 124,
 'Salvadoran restaurant': 125,
 'Dominican restaurant': 126,
 'Pan-Latin restaurant': 127,
 'Cajun restaurant': 128,
 'Modern Indian restaurant': 129,
 'Punjabi restaurant': 130,
 'Indian restaurant': 131,
 'North Eastern Indian restaurant': 132,
 'South Asian restaurant': 133,
 'Seafood market': 134,
 'Grill': 135,
 'Pakistani restaurant': 136,
 'Dumpling restaurant': 137,
 'South American restaurant': 138,
 'Catering': 139,
 'Biryani restaurant': 140,
 'Afghani restaurant': 141,
 'Venezuelan restaurant': 142,
 'Mongolian barbecue restaurant': 143,
 'Dessert restaurant': 144,
 'Creole restaurant': 145,
 'Peruvian restaurant': 146,
 'Small plates restaurant': 147,
 'Oyster bar restaurant': 148,
 'Espresso bar': 149,
 'Pancake restaurant': 150,
 'Takeout restaurant': 151,
 'Mexican torta restaurant': 152,
 'Southeast Asian restaurant': 153,
 'Japanese curry restaurant': 154,
 'Fish & chips restaurant': 155,
 'Californian restaurant': 156,
 'Jamaican restaurant': 157,
 'Southwestern restaurant (US)': 158,
 'Restaurant': 159,
 'Restaurant or cafe': 160,
 'Grill store': 161,
 'Bark supplier': 162,
 'Snack bar': 163,
 'Barber supply store': 164,
 'Guatemalan restaurant': 165,
 'Eyebrow bar': 166,
 'Seafood wholesaler': 167,
 'Indonesian restaurant': 168,
 'Restaurant supply store': 169,
 'Ethiopian restaurant': 170,
 'Barn': 171,
 'Bartending school': 172,
 'Filipino restaurant': 173,
 'Gay bar': 174,
 'Wedding buffet': 175,
 'Singaporean restaurant': 176,
 'Wholesale bakery': 177,
 'Hunan restaurant': 178,
 'Poke bar': 179,
 'Taiwanese restaurant': 180,
 'Self-catering accommodation': 181,
 'Sweets and dessert buffet': 182,
 'Honduran restaurant': 183,
 'Barber school': 184,
 'Piano bar': 185,
 'Subaru dealer': 186,
 'Barrister': 187,
 'Bar stool supplier': 188,
 'Portuguese restaurant': 189,
 'Dart bar': 190,
 'Irish restaurant': 191,
 'Hoagie restaurant': 192,
 'Argentinian restaurant': 193,
 'Jewish restaurant': 194,
 'Ecuadorian restaurant': 195,
 'Cider bar': 196,
 'Yakiniku restaurant': 197,
 'Belgian restaurant': 198,
 'Dance restaurant': 199,
 'Scandinavian restaurant': 200,
 'Cabaret club': 201,
 'Barbecue area': 202,
 'Norwegian restaurant': 203,
 'Polish restaurant': 204,
 'Hong Kong style fast food restaurant': 205,
 'Canadian restaurant': 206,
 'Haitian restaurant': 207,
 'Hyperbaric medicine physician': 208,
 'Swedish restaurant': 209,
 'Contemporary Louisiana restaurant': 210,
 'Ukrainian restaurant': 211,
 'Shabu-shabu restaurant': 212,
 'Chophouse restaurant': 213,
 'Western restaurant': 214,
 'Conveyor belt sushi restaurant': 215,
 'Bar restaurant furniture store': 216,
 'Pueblan restaurant': 217,
 'Pozole restaurant': 218,
 'Nepalese restaurant': 219,
 'Barrel supplier': 220,
 'Seafood donburi restaurant': 221,
 'Cape Verdean restaurant': 222,
 'Continental restaurant': 223,
 'Bariatric surgeon': 224,
 'Bar PMU': 225,
 'Country food restaurant': 226,
 'Sundae restaurant': 227,
 'Fondue restaurant': 228,
 'Tonkatsu restaurant': 229,
 'Berry restaurant': 230,
 'Seafood': 231,
 'Bangladeshi restaurant': 232,
 'Dan Dan noodle restaurant': 233,
 'Cambodian restaurant': 234,
 'Childrens party buffet': 235,
 'Bakery equipment': 236,
 'Sukiyaki and Shabu Shabu restaurant': 237,
 'Indian Muslim restaurant': 238,
 'Pacific Northwest restaurant (US)': 239,
 'British restaurant': 240,
 'Uzbeki restaurant': 241,
 'Georgian restaurant': 242,
 'Mid-Atlantic restaurant (US)': 243,
 'Central American restaurant': 244,
 'Takoyaki restaurant': 245,
 'Fish and seafood restaurant': 246,
 'Yucatan restaurant': 247,
 'Military barracks': 248,
 'Floridian restaurant': 249,
 'Eritrean restaurant': 250,
 'Burmese restaurant': 251,
 'Dutch restaurant': 252,
 'Momo restaurant': 253,
 'Shanghainese restaurant': 254,
 'Basque restaurant': 255,
 'Kerala restaurant': 256,
 'Syrian restaurant': 257,
 'Tuscan restaurant': 258,
 'Raclette restaurant': 259,
 'Tiki bar': 260,
 'Nicaraguan restaurant': 261,
 'Self service restaurant': 262,
 'Po’ boys restaurant': 263,
 'Australian restaurant': 264,
 'Chilean restaurant': 265,
 'Stand bar': 266,
 'Japanese regional restaurant': 267,
 'Croatian restaurant': 268,
 'Paraguayan restaurant': 269,
 'Lithuanian restaurant': 270,
 'Wok restaurant': 271,
 'Japanese sweets restaurant': 272,
 'Kyoto style Japanese restaurant': 273,
 'Bar tabac': 274,
 'Angler fish restaurant': 275,
 'Sicilian restaurant': 276,
 'Oaxacan restaurant': 277,
 'Uruguayan restaurant': 278,
 'Yemenite restaurant': 279,
 'Sri Lankan restaurant': 280,
 'Indian sizzler restaurant': 281,
 'Tofu restaurant': 282,
 'Costa Rican restaurant': 283,
 'New England restaurant': 284,
 'Seafood farm': 285,
 'Hakka restaurant': 286,
 'Kushiyaki restaurant': 287,
 'Chinese bakery': 288,
 'Serbian restaurant': 289,
 'Fugu restaurant': 290,
 'Army barracks': 291,
 'North African restaurant': 292,
 'Modern izakaya restaurants': 293,
 'Haute French restaurant': 294,
 'Pacific Rim restaurant': 295,
 'Pennsylvania Dutch restaurant': 296,
 'Swiss restaurant': 297,
 'Czech restaurant': 298,
 'Macrobiotic restaurant': 299,
 'Korean rib restaurant': 300,
 'Catalonian restaurant': 301,
 'Soondae restaurant': 302,
 'Syokudo and Teishoku restaurant': 303,
 'Goan restaurant': 304,
 'Native American restaurant': 305,
 'Couscous restaurant': 306,
 'New Zealand restaurant': 307,
 'Porridge restaurant': 308,
 'Roman restaurant': 309,
 'Tibetan restaurant': 310,
 'Tempura restaurant': 311,
 'Offal barbecue restaurant': 312,
 'Korean beef restaurant': 313,
 'Tunisian restaurant': 314,
 'Chesapeake restaurant': 315,
 'Asturian restaurant': 316,
 'Kazakhstani restaurant': 317,
 'Japanized western restaurant': 318,
 'Shawarma restaurant': 319,
 'Danish restaurant': 320,
 'Anago restaurant': 321,
 'Dried seafood store': 322,
 'Salsa bar': 323,
 'Cured ham bar': 324,
 'Seafood store': 325,
 'Modern British restaurant': 326,
 'Kaiseki restaurant': 327,
 'Fujian restaurant': 328,
 'Katsudon restaurant': 329,
 'Turkmen restaurant': 330,
 'Hungarian restaurant': 331,
 'Anhui restaurant': 332,
 'Shandong restaurant': 333,
 'Madrilian restaurant': 334,
 'Cold noodle restaurant': 335,
 'Obanzai restaurant': 336,
 'Icelandic restaurant': 337,
 'Yakisoba Restaurant': 338,
 'Champon noodle restaurant': 339,
 'Welsh restaurant': 340,
 'South Indian restaurant': 341,
 'Valencian restaurant': 342,
 'Scottish restaurant': 343,
 'Satay restaurant': 344,
 'Chettinad restaurant': 345,
 'Sfiha restaurant': 346,
 'Mutton barbecue restaurant': 347,
 'Steamboat restaurant': 348,
 'Sundanese restaurant': 349,
 'Tempura donburi restaurant': 350}

Segunda Variante

In [338]:
import pandas as pd
import random

def top_categorias(df, n=10):
    """
    Calcula el top N de categorías más frecuentes en las columnas de categorías.
    """
    categorias = pd.concat([df['Categoria1'], df['Categoria2'], df['Categoria3'], df['Categoria4'], df['Categoria5']])
    conteo_categorias = categorias.value_counts()
    return conteo_categorias.head(n)

def mostrar_top_categorias(top_n, diccionario_categorias):
    """
    Muestra el top N de categorías con sus nombres legibles.
    """
    print("Top Categorías:")
    for categoria_id, conteo in top_n.items():
        nombre_categoria = diccionario_categorias.get(categoria_id, "Categoría Desconocida")
        print(f"- {nombre_categoria}: {conteo} menciones")

def recomendar_restaurantes(df, diccionario_categorias, estado, promedio_minimo=None, valoraciones_minimas=None, categoria_deseada=None, atributos=None, restaurante_visitado=None, n=3):
    """
    Recomienda restaurantes basándose en las preferencias del usuario.
    """

    # 1. Filtrar por estado
    df_filtrado = df[df['Estado'] == estado].copy()

    # 2. Filtrar por promedio mínimo (si se proporciona)
    if promedio_minimo is not None:
        df_filtrado = df_filtrado[df_filtrado['Promedio'] >= promedio_minimo]

    # 3. Filtrar por valoraciones mínimas (si se proporciona)
    if valoraciones_minimas is not None:
        df_filtrado = df_filtrado[df_filtrado['Valoraciones'] >= valoraciones_minimas]

    # 4. Filtrar por categoría (si se proporciona)
    if categoria_deseada is not None:
        df_filtrado = df_filtrado[(df_filtrado['Categoria1'] == categoria_deseada) |
                                  (df_filtrado['Categoria2'] == categoria_deseada) |
                                  (df_filtrado['Categoria3'] == categoria_deseada) |
                                  (df_filtrado['Categoria4'] == categoria_deseada) |
                                  (df_filtrado['Categoria5'] == categoria_deseada)]

    # 5. Filtrar por atributos adicionales (si se proporcionan)
    if atributos:
        for atributo, valor in atributos.items():
            df_filtrado = df_filtrado[df_filtrado[atributo] == valor]

    # 6. Eliminar restaurante visitado (si se proporciona)
    if restaurante_visitado:
        df_filtrado = df_filtrado[df_filtrado['Nombre'] != restaurante_visitado]

    # 7. Selección aleatoria de restaurantes
    if len(df_filtrado) == 0:
        print("No se encontraron restaurantes que coincidan con tus criterios.")
        return None

    recomendaciones = df_filtrado.sample(n=min(n, len(df_filtrado)))

    # 8. Mostrar recomendaciones
    print("\nRestaurantes Recomendados:")
    for idx, restaurante in recomendaciones.iterrows():
        print(f"\nRecomendación #{idx + 1}:")
        print(f"  Nombre: {restaurante['Nombre']}")
        print(f"  Promedio: {restaurante['Promedio']}")
        print(f"  Valoraciones: {restaurante['Valoraciones']}")

        # Mostrar categorías
        categorias = []
        for i in range(1, 6):
            categoria_columna = f'Categoria{i}'
            categoria_id = restaurante[categoria_columna]
            if categoria_id != 0:  # Asumiendo que 0 significa "sin categoría"
                nombre_categoria = diccionario_categorias.get(categoria_id, "Categoría Desconocida")
                categorias.append(nombre_categoria)
        print(f"  Categorías: {', '.join(categorias)}")

        # Mostrar atributos adicionales (Takeout, Delivery, etc.)
        atributos_presentes = []
        for columna in ['Takeout', 'Delivery', 'Asientos Discapacitados', 'Estacionamiento Discapacitados',
                        'Almuerzo', 'Cena', 'Comer Solo', 'Grupos', 'Turistas', 'Debito', 'NFC', 'Credito', 'Servicio Rapido']:
            if restaurante[columna] == 1:
                atributos_presentes.append(columna)
        print(f"  Atributos: {', '.join(atributos_presentes)}")

def main():
    """
    Función principal para ejecutar el algoritmo de recomendación.
    """
    global ML_BASE, diccionario_categorias  # Asegúrate de que ML_BASE y diccionario_categorias estén definidos globalmente o pasados como argumentos

    # Mostrar top categorías
    top_n = top_categorias(ML_BASE)
    mostrar_top_categorias(top_n, diccionario_categorias)

    # Obtener filtros del usuario
    estado = input("Ingrese el Estado para filtrar: ")
    promedio_minimo_str = input("Ingrese el Promedio Mínimo (0-5, opcional, presione Enter para omitir): ")
    valoraciones_minimas_str = input("Ingrese la Cantidad Mínima de Valoraciones (opcional, presione Enter para omitir): ")
    categoria_deseada_str = input("Ingrese el ID de la categoría deseada (opcional, presione Enter para omitir): ")

    # Convertir las entradas del usuario a los tipos de datos correctos
    promedio_minimo = float(promedio_minimo_str) if promedio_minimo_str else None
    valoraciones_minimas = int(valoraciones_minimas_str) if valoraciones_minimas_str else None
    categoria_deseada = int(categoria_deseada_str) if categoria_deseada_str else None

    # Crear diccionario de atributos adicionales
    atributos = {}
    if input("¿Desea Takeout? (si/no): ").lower() == 'si':
        atributos['Takeout'] = 1
    if input("¿Desea Delivery? (si/no): ").lower() == 'si':
        atributos['Delivery'] = 1
    if input("¿Requiere Asientos para Discapacitados? (si/no): ").lower() == 'si':
        atributos['Asientos Discapacitados'] = 1
    if input("¿Requiere Estacionamiento para Discapacitados? (si/no): ").lower() == 'si':
        atributos['Estacionamiento Discapacitados'] = 1
    if input("¿Desea Almuerzo? (si/no): ").lower() == 'si':
        atributos['Almuerzo'] = 1
    if input("¿Desea Cena? (si/no): ").lower() == 'si':
        atributos['Cena'] = 1
    if input("¿Desea Comer Solo? (si/no): ").lower() == 'si':
        atributos['Comer Solo'] = 1
    if input("¿Desea Grupos? (si/no): ").lower() == 'si':
        atributos['Grupos'] = 1
    if input("¿Desea Turistas? (si/no): ").lower() == 'si':
        atributos['Turistas'] = 1
    if input("¿Desea pagar con Debito? (si/no): ").lower() == 'si':
        atributos['Debito'] = 1
    if input("¿Desea pagar con NFC? (si/no): ").lower() == 'si':
        atributos['NFC'] = 1
    if input("¿Desea pagar con Credito? (si/no): ").lower() == 'si':
        atributos['Credito'] = 1
    if input("¿Desea Servicio Rapido? (si/no): ").lower() == 'si':
        atributos['Servicio Rapido'] = 1

    nombre_restaurante_visitado = input("Ingrese el nombre de un restaurante que ya haya visitado (opcional, presione Enter para omitir): ")

    # Recomendar restaurantes
    recomendar_restaurantes(ML_BASE, diccionario_categorias, estado, promedio_minimo, valoraciones_minimas, categoria_deseada, atributos, nombre_restaurante_visitado)

# Ejecutar la función principal
if __name__ == "__main__":
    # Asegúrate de que ML_BASE y diccionario_categorias estén cargados antes de ejecutar main()
    # Ejemplo:
    # ML_BASE = pd.read_csv("tu_archivo.csv")
    # diccionario_categorias = cargar_diccionario_desde_archivo("diccionario_categorias.json")
    main()

Top Categorías:
- Categoría Desconocida: 789719 menciones
- Categoría Desconocida: 90144 menciones
- Categoría Desconocida: 28735 menciones
- Categoría Desconocida: 23669 menciones
- Categoría Desconocida: 23437 menciones
- Categoría Desconocida: 17129 menciones
- Categoría Desconocida: 17106 menciones
- Categoría Desconocida: 13172 menciones
- Categoría Desconocida: 11702 menciones
- Categoría Desconocida: 11043 menciones
No se encontraron restaurantes que coincidan con tus criterios.

In [344]:
def recomendar_restaurantes(df, diccionario_categorias, estado, promedio_minimo=None, valoraciones_minimas=None, categoria_deseada=None, atributos=None, restaurante_visitado=None, n=3):
    """
    Recomienda restaurantes basándose en las preferencias del usuario.
    """

    # 1. Filtrar por estado
    df_filtrado = df[df['Estado'] == estado].copy()

    # 2. Filtrar por promedio mínimo (si se proporciona)
    if promedio_minimo is not None:
        df_filtrado = df_filtrado[df_filtrado['Promedio'] >= promedio_minimo]

    # 3. Filtrar por valoraciones mínimas (si se proporciona)
    if valoraciones_minimas is not None:
        df_filtrado = df_filtrado[df_filtrado['Valoraciones'] >= valoraciones_minimas]

    # 4. Filtrar por categoría (si se proporciona)
    if categoria_deseada is not None:
        df_filtrado = df_filtrado[(df_filtrado['Categoria1'] == categoria_deseada) |
                                  (df_filtrado['Categoria2'] == categoria_deseada) |
                                  (df_filtrado['Categoria3'] == categoria_deseada) |
                                  (df_filtrado['Categoria4'] == categoria_deseada) |
                                  (df_filtrado['Categoria5'] == categoria_deseada)]

    # 5. Filtrar por atributos adicionales (si se proporcionan)
    if atributos:
        for atributo, valor in atributos.items():
            df_filtrado = df_filtrado[df_filtrado[atributo] == valor]

    # 6. Eliminar restaurante visitado (si se proporciona)
    if restaurante_visitado:
        df_filtrado = df_filtrado[df_filtrado['Nombre'] != restaurante_visitado]

    # 7. Selección aleatoria de restaurantes
    if len(df_filtrado) == 0:
        print("No se encontraron restaurantes que coincidan con tus criterios. Mostrando restaurantes aleatorios del estado.")
        df_filtrado = df[df['Estado'] == estado].copy()  # Restaurantes aleatorios del estado
        if len(df_filtrado) == 0:
            print("No se encontraron restaurantes en este estado.")
            return None

    recomendaciones = df_filtrado.sample(n=min(n, len(df_filtrado)))

    # 8. Mostrar recomendaciones
    print("\nRestaurantes Recomendados:")
    for idx, restaurante in recomendaciones.iterrows():
        print(f"\nRecomendación #{idx + 1}:")
        print(f"  Nombre: {restaurante['Nombre']}")
        print(f"  Promedio: {restaurante['Promedio']}")
        print(f"  Valoraciones: {restaurante['Valoraciones']}")

        # Mostrar categorías
        categorias = []
        for i in range(1, 6):
            categoria_columna = f'Categoria{i}'
            categoria_id = restaurante[categoria_columna]
            if categoria_id != 0:  # Asumiendo que 0 significa "sin categoría"
                nombre_categoria = diccionario_categorias.get(str(categoria_id), "Categoría Desconocida")
                categorias.append(nombre_categoria)
        print(f"  Categorías: {', '.join(categorias)}")

        # Mostrar atributos adicionales (Takeout, Delivery, etc.)
        atributos_presentes = []
        for columna in ['Takeout', 'Delivery', 'Asientos Discapacitados', 'Estacionamiento Discapacitados',
                        'Almuerzo', 'Cena', 'Comer Solo', 'Grupos', 'Turistas', 'Debito', 'NFC', 'Credito', 'Servicio Rapido']:
            if restaurante[columna] == 1:
                atributos_presentes.append(columna)
        print(f"  Atributos: {', '.join(atributos_presentes)}")



        # Recomendar restaurantes

recomendar_restaurantes(ML_BASE, diccionario_categorias, 'Texas')

Restaurantes Recomendados:

Recomendación #222167:
  Nombre: Pizza Hut Express
  Promedio: 3.9
  Valoraciones: 24
  Categorías: Categoría Desconocida
  Atributos: Takeout, Delivery, Asientos Discapacitados, Almuerzo, Cena, Debito

Recomendación #40509:
  Nombre: Groholski's
  Promedio: 4.6
  Valoraciones: 24
  Categorías: Categoría Desconocida, Categoría Desconocida, Categoría Desconocida
  Atributos: Takeout, Delivery, Asientos Discapacitados, Turistas

Recomendación #162750:
  Nombre: Mitas Hill Vineyard
  Promedio: 4.1
  Valoraciones: 75
  Categorías: Categoría Desconocida, Categoría Desconocida, Categoría Desconocida, Categoría Desconocida
  Atributos: Delivery, Asientos Discapacitados

In [346]:
def recomendar_restaurantes(df, diccionario_categorias, estado, promedio_minimo=None, valoraciones_minimas=None, categoria_deseada=None, atributos=None, restaurante_visitado=None, n=3):
    """
    Recomienda restaurantes basándose en las preferencias del usuario.
    """

    # 1. Filtrar por estado
    df_filtrado = df[df['Estado'] == estado].copy()

    # 2. Filtrar por promedio mínimo (si se proporciona)
    if promedio_minimo is not None:
        df_filtrado = df_filtrado[df_filtrado['Promedio'] >= promedio_minimo]

    # 3. Filtrar por valoraciones mínimas (si se proporciona)
    if valoraciones_minimas is not None:
        df_filtrado = df_filtrado[df_filtrado['Valoraciones'] >= valoraciones_minimas]

    # 4. Filtrar por categoría (si se proporciona)
    if categoria_deseada is not None:
        categoria_deseada = int(categoria_deseada)  # Asegurar que sea un entero
        df_filtrado = df_filtrado[(df_filtrado['Categoria1'] == categoria_deseada) |
                                  (df_filtrado['Categoria2'] == categoria_deseada) |
                                  (df_filtrado['Categoria3'] == categoria_deseada) |
                                  (df_filtrado['Categoria4'] == categoria_deseada) |
                                  (df_filtrado['Categoria5'] == categoria_deseada)]

    # 5. Filtrar por atributos adicionales (si se proporcionan)
    if atributos:
        for atributo, valor in atributos.items():
            df_filtrado = df_filtrado[df_filtrado[atributo] == valor]

    # 6. Eliminar restaurante visitado (si se proporciona)
    if restaurante_visitado:
        df_filtrado = df_filtrado[df_filtrado['Nombre'] != restaurante_visitado]

    # 7. Selección aleatoria de restaurantes
    if len(df_filtrado) == 0:
        print("No se encontraron restaurantes que coincidan con tus criterios. Mostrando restaurantes aleatorios del estado.")
        df_filtrado = df[df['Estado'] == estado].copy()  # Restaurantes aleatorios del estado
        if len(df_filtrado) == 0:
            print("No se encontraron restaurantes en este estado.")
            return None

    recomendaciones = df_filtrado.sample(n=min(n, len(df_filtrado)))

    # 8. Mostrar recomendaciones
    print("\nRestaurantes Recomendados:")
    for idx, restaurante in recomendaciones.iterrows():
        print(f"\nRecomendación #{idx + 1}:")
        print(f"  Nombre: {restaurante['Nombre']}")
        print(f"  Promedio: {restaurante['Promedio']}")
        print(f"  Valoraciones: {restaurante['Valoraciones']}")

        # Mostrar categorías
        categorias = []
        for i in range(1, 6):
            categoria_columna = f'Categoria{i}'
            categoria_id = restaurante[categoria_columna]
            if categoria_id != 0:  # Asumiendo que 0 significa "sin categoría"
                nombre_categoria = diccionario_categorias.get(str(categoria_id), "Categoría Desconocida")
                categorias.append(nombre_categoria)
        print(f"  Categorías: {', '.join(categorias)}")

        # Mostrar atributos adicionales (Takeout, Delivery, etc.)
        atributos_presentes = []
        for columna in ['Takeout', 'Delivery', 'Asientos Discapacitados', 'Estacionamiento Discapacitados',
                        'Almuerzo', 'Cena', 'Comer Solo', 'Grupos', 'Turistas', 'Debito', 'NFC', 'Credito', 'Servicio Rapido']:
            if restaurante[columna] == 1:
                atributos_presentes.append(columna)
        print(f"  Atributos: {', '.join(atributos_presentes)}")

In [ ]:
recomendar_restaurantes(ML_BASE, diccionario_categorias, 'Texas')

Restaurantes Recomendados:

Recomendación #150302:
  Nombre: Sam's Club Bakery
  Promedio: 4.4
  Valoraciones: 8
  Categorías: Categoría Desconocida, Categoría Desconocida, Categoría Desconocida
  Atributos: Takeout, Delivery, Asientos Discapacitados

Recomendación #163223:
  Nombre: Subway
  Promedio: 3.8
  Valoraciones: 84
  Categorías: Categoría Desconocida
  Atributos: Takeout, Delivery, Asientos Discapacitados, Almuerzo, Cena, Comer Solo, Turistas, Debito

Recomendación #206746:
  Nombre: Un Mundo De Sabor
  Promedio: 4.8
  Valoraciones: 67
  Categorías: Categoría Desconocida, Categoría Desconocida
  Atributos: Takeout, Delivery, Estacionamiento Discapacitados, Cena, Comer Solo, Debito, NFC, Credito

In [348]:
diccionario_categorias

{'French restaurant': 0,
 'French steakhouse restaurant': 1,
 'Fusion restaurant': 2,
 'Modern French restaurant': 3,
 'Pizza restaurant': 4,
 'Turkish restaurant': 5,
 'Gyro restaurant': 6,
 'Halal restaurant': 7,
 'Mediterranean restaurant': 8,
 'Middle Eastern restaurant': 9,
 'Sushi restaurant': 10,
 'Burrito restaurant': 11,
 'Raw food restaurant': 12,
 'Seafood restaurant': 13,
 'Taco restaurant': 14,
 'Asian restaurant': 15,
 'Buffet restaurant': 16,
 'Chinese restaurant': 17,
 'Hot pot restaurant': 18,
 'Japanese restaurant': 19,
 'Fine dining restaurant': 20,
 'American restaurant': 21,
 'Brunch restaurant': 22,
 'Vegetarian restaurant': 23,
 'Bistro': 24,
 'Caribbean restaurant': 25,
 'Cocktail bar': 26,
 'Hookah bar': 27,
 'Austrian restaurant': 28,
 'European restaurant': 29,
 'German restaurant': 30,
 'Pizza Takeout': 31,
 'Breakfast restaurant': 32,
 'Gluten-free restaurant': 33,
 'Delivery Restaurant': 34,
 'Takeout Restaurant': 35,
 'Catering food and drink supplier': 36,
 'Mexican restaurant': 37,
 'Vegan restaurant': 38,
 'Izakaya restaurant': 39,
 'Authentic Japanese restaurant': 40,
 'Udon noodle restaurant': 41,
 'Yakitori restaurant': 42,
 'Laotian restaurant': 43,
 'Pho restaurant': 44,
 'Thai restaurant': 45,
 'Vietnamese restaurant': 46,
 'Asian fusion restaurant': 47,
 'Fast food restaurant': 48,
 'Lunch restaurant': 49,
 'Bulgarian restaurant': 50,
 'Eastern European restaurant': 51,
 'Romanian restaurant': 52,
 'Russian restaurant': 53,
 'Teppanyaki restaurant': 54,
 'Chicken restaurant': 55,
 'Spanish restaurant': 56,
 'Hawaiian restaurant': 57,
 'Polynesian restaurant': 58,
 'Hamburger restaurant': 59,
 'Japanese steakhouse': 60,
 'Bar & grill': 61,
 'Barbecue restaurant': 62,
 'Karaoke bar': 63,
 'Sports bar': 64,
 'Italian restaurant': 65,
 'Organic restaurant': 66,
 'Health food restaurant': 67,
 'New American restaurant': 68,
 'Traditional American restaurant': 69,
 'Tapas restaurant': 70,
 'Pan-Asian restaurant': 71,
 'Dim sum restaurant': 72,
 'Mandarin restaurant': 73,
 'Moroccan restaurant': 74,
 'Ramen restaurant': 75,
 'Rice restaurant': 76,
 'African restaurant': 77,
 'East African restaurant': 78,
 'South African restaurant': 79,
 'West African restaurant': 80,
 'Wine bar': 81,
 'Egyptian restaurant': 82,
 'Lebanese restaurant': 83,
 'Down home cooking restaurant': 84,
 'Diner': 85,
 'Family restaurant': 86,
 'English restaurant': 87,
 'Neapolitan restaurant': 88,
 'Northern Italian restaurant': 89,
 'Southern Italian restaurant': 90,
 'Chicken wings restaurant': 91,
 'Korean barbecue restaurant': 92,
 'Korean restaurant': 93,
 'Soup restaurant': 94,
 'Israeli restaurant': 95,
 'Kosher restaurant': 96,
 'Sichuan restaurant': 97,
 'Hot dog restaurant': 98,
 'Meat dish restaurant': 99,
 'Southern restaurant (US)': 100,
 'Latin American restaurant': 101,
 'Eclectic restaurant': 102,
 'Tex-Mex restaurant': 103,
 'Malaysian restaurant': 104,
 'Greek restaurant': 105,
 'Live music bar': 106,
 'Tapas bar': 107,
 'Ethnic restaurant': 108,
 'Traditional restaurant': 109,
 'Soul food restaurant': 110,
 'Armenian restaurant': 111,
 'Cantonese restaurant': 112,
 'Cheesesteak restaurant': 113,
 'Falafel restaurant': 114,
 'Modern European restaurant': 115,
 'Wedding bakery': 116,
 'Persian restaurant': 117,
 'Delivery Chinese restaurant': 118,
 'Brazilian restaurant': 119,
 'Cuban restaurant': 120,
 'Chinese noodle restaurant': 121,
 'Nuevo Latino restaurant': 122,
 'Colombian restaurant': 123,
 'Puerto Rican restaurant': 124,
 'Salvadoran restaurant': 125,
 'Dominican restaurant': 126,
 'Pan-Latin restaurant': 127,
 'Cajun restaurant': 128,
 'Modern Indian restaurant': 129,
 'Punjabi restaurant': 130,
 'Indian restaurant': 131,
 'North Eastern Indian restaurant': 132,
 'South Asian restaurant': 133,
 'Seafood market': 134,
 'Grill': 135,
 'Pakistani restaurant': 136,
 'Dumpling restaurant': 137,
 'South American restaurant': 138,
 'Catering': 139,
 'Biryani restaurant': 140,
 'Afghani restaurant': 141,
 'Venezuelan restaurant': 142,
 'Mongolian barbecue restaurant': 143,
 'Dessert restaurant': 144,
 'Creole restaurant': 145,
 'Peruvian restaurant': 146,
 'Small plates restaurant': 147,
 'Oyster bar restaurant': 148,
 'Espresso bar': 149,
 'Pancake restaurant': 150,
 'Takeout restaurant': 151,
 'Mexican torta restaurant': 152,
 'Southeast Asian restaurant': 153,
 'Japanese curry restaurant': 154,
 'Fish & chips restaurant': 155,
 'Californian restaurant': 156,
 'Jamaican restaurant': 157,
 'Southwestern restaurant (US)': 158,
 'Restaurant': 159,
 'Restaurant or cafe': 160,
 'Grill store': 161,
 'Bark supplier': 162,
 'Snack bar': 163,
 'Barber supply store': 164,
 'Guatemalan restaurant': 165,
 'Eyebrow bar': 166,
 'Seafood wholesaler': 167,
 'Indonesian restaurant': 168,
 'Restaurant supply store': 169,
 'Ethiopian restaurant': 170,
 'Barn': 171,
 'Bartending school': 172,
 'Filipino restaurant': 173,
 'Gay bar': 174,
 'Wedding buffet': 175,
 'Singaporean restaurant': 176,
 'Wholesale bakery': 177,
 'Hunan restaurant': 178,
 'Poke bar': 179,
 'Taiwanese restaurant': 180,
 'Self-catering accommodation': 181,
 'Sweets and dessert buffet': 182,
 'Honduran restaurant': 183,
 'Barber school': 184,
 'Piano bar': 185,
 'Subaru dealer': 186,
 'Barrister': 187,
 'Bar stool supplier': 188,
 'Portuguese restaurant': 189,
 'Dart bar': 190,
 'Irish restaurant': 191,
 'Hoagie restaurant': 192,
 'Argentinian restaurant': 193,
 'Jewish restaurant': 194,
 'Ecuadorian restaurant': 195,
 'Cider bar': 196,
 'Yakiniku restaurant': 197,
 'Belgian restaurant': 198,
 'Dance restaurant': 199,
 'Scandinavian restaurant': 200,
 'Cabaret club': 201,
 'Barbecue area': 202,
 'Norwegian restaurant': 203,
 'Polish restaurant': 204,
 'Hong Kong style fast food restaurant': 205,
 'Canadian restaurant': 206,
 'Haitian restaurant': 207,
 'Hyperbaric medicine physician': 208,
 'Swedish restaurant': 209,
 'Contemporary Louisiana restaurant': 210,
 'Ukrainian restaurant': 211,
 'Shabu-shabu restaurant': 212,
 'Chophouse restaurant': 213,
 'Western restaurant': 214,
 'Conveyor belt sushi restaurant': 215,
 'Bar restaurant furniture store': 216,
 'Pueblan restaurant': 217,
 'Pozole restaurant': 218,
 'Nepalese restaurant': 219,
 'Barrel supplier': 220,
 'Seafood donburi restaurant': 221,
 'Cape Verdean restaurant': 222,
 'Continental restaurant': 223,
 'Bariatric surgeon': 224,
 'Bar PMU': 225,
 'Country food restaurant': 226,
 'Sundae restaurant': 227,
 'Fondue restaurant': 228,
 'Tonkatsu restaurant': 229,
 'Berry restaurant': 230,
 'Seafood': 231,
 'Bangladeshi restaurant': 232,
 'Dan Dan noodle restaurant': 233,
 'Cambodian restaurant': 234,
 'Childrens party buffet': 235,
 'Bakery equipment': 236,
 'Sukiyaki and Shabu Shabu restaurant': 237,
 'Indian Muslim restaurant': 238,
 'Pacific Northwest restaurant (US)': 239,
 'British restaurant': 240,
 'Uzbeki restaurant': 241,
 'Georgian restaurant': 242,
 'Mid-Atlantic restaurant (US)': 243,
 'Central American restaurant': 244,
 'Takoyaki restaurant': 245,
 'Fish and seafood restaurant': 246,
 'Yucatan restaurant': 247,
 'Military barracks': 248,
 'Floridian restaurant': 249,
 'Eritrean restaurant': 250,
 'Burmese restaurant': 251,
 'Dutch restaurant': 252,
 'Momo restaurant': 253,
 'Shanghainese restaurant': 254,
 'Basque restaurant': 255,
 'Kerala restaurant': 256,
 'Syrian restaurant': 257,
 'Tuscan restaurant': 258,
 'Raclette restaurant': 259,
 'Tiki bar': 260,
 'Nicaraguan restaurant': 261,
 'Self service restaurant': 262,
 'Po’ boys restaurant': 263,
 'Australian restaurant': 264,
 'Chilean restaurant': 265,
 'Stand bar': 266,
 'Japanese regional restaurant': 267,
 'Croatian restaurant': 268,
 'Paraguayan restaurant': 269,
 'Lithuanian restaurant': 270,
 'Wok restaurant': 271,
 'Japanese sweets restaurant': 272,
 'Kyoto style Japanese restaurant': 273,
 'Bar tabac': 274,
 'Angler fish restaurant': 275,
 'Sicilian restaurant': 276,
 'Oaxacan restaurant': 277,
 'Uruguayan restaurant': 278,
 'Yemenite restaurant': 279,
 'Sri Lankan restaurant': 280,
 'Indian sizzler restaurant': 281,
 'Tofu restaurant': 282,
 'Costa Rican restaurant': 283,
 'New England restaurant': 284,
 'Seafood farm': 285,
 'Hakka restaurant': 286,
 'Kushiyaki restaurant': 287,
 'Chinese bakery': 288,
 'Serbian restaurant': 289,
 'Fugu restaurant': 290,
 'Army barracks': 291,
 'North African restaurant': 292,
 'Modern izakaya restaurants': 293,
 'Haute French restaurant': 294,
 'Pacific Rim restaurant': 295,
 'Pennsylvania Dutch restaurant': 296,
 'Swiss restaurant': 297,
 'Czech restaurant': 298,
 'Macrobiotic restaurant': 299,
 'Korean rib restaurant': 300,
 'Catalonian restaurant': 301,
 'Soondae restaurant': 302,
 'Syokudo and Teishoku restaurant': 303,
 'Goan restaurant': 304,
 'Native American restaurant': 305,
 'Couscous restaurant': 306,
 'New Zealand restaurant': 307,
 'Porridge restaurant': 308,
 'Roman restaurant': 309,
 'Tibetan restaurant': 310,
 'Tempura restaurant': 311,
 'Offal barbecue restaurant': 312,
 'Korean beef restaurant': 313,
 'Tunisian restaurant': 314,
 'Chesapeake restaurant': 315,
 'Asturian restaurant': 316,
 'Kazakhstani restaurant': 317,
 'Japanized western restaurant': 318,
 'Shawarma restaurant': 319,
 'Danish restaurant': 320,
 'Anago restaurant': 321,
 'Dried seafood store': 322,
 'Salsa bar': 323,
 'Cured ham bar': 324,
 'Seafood store': 325,
 'Modern British restaurant': 326,
 'Kaiseki restaurant': 327,
 'Fujian restaurant': 328,
 'Katsudon restaurant': 329,
 'Turkmen restaurant': 330,
 'Hungarian restaurant': 331,
 'Anhui restaurant': 332,
 'Shandong restaurant': 333,
 'Madrilian restaurant': 334,
 'Cold noodle restaurant': 335,
 'Obanzai restaurant': 336,
 'Icelandic restaurant': 337,
 'Yakisoba Restaurant': 338,
 'Champon noodle restaurant': 339,
 'Welsh restaurant': 340,
 'South Indian restaurant': 341,
 'Valencian restaurant': 342,
 'Scottish restaurant': 343,
 'Satay restaurant': 344,
 'Chettinad restaurant': 345,
 'Sfiha restaurant': 346,
 'Mutton barbecue restaurant': 347,
 'Steamboat restaurant': 348,
 'Sundanese restaurant': 349,
 'Tempura donburi restaurant': 350}